INSERT INTO schools
values ( 1, "moro", "moro@a.it"),
( 2, "spalla", "spalla@a.it"),
( 3, "zanelli", "zanelli@a.it"),
( 4, "canossa", "canossa@a.it"),
( 5, "chierici", "chierici@a.it"),
( 6, "motti", "motti@a.it"),
( 7, "nobili", "nobili@a.it"),
( 8, "iti", "iti@a.it"),
( 9, "ipsia", "ipsia@a.it"),
( 10, "bus", "bus@a.it"),
( 11, "levi", "levi@a.it"),
( 12, "secchi", "secchi@a.it"),
( 13, "iodi", "iodi@a.it"),
( 14, "galvani", "galvani@a.it"),
( 15, "iess", "iess@a.it");
